name: "Pull request"
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

        # "prepare" hook on `bun install` runs `bun run build`
      - name: Setup environment
        uses: ./.github/actions/setup-env

      - name: Run tests
        run: bun run test