name: "Pull request"
on:
  pull_request:
    # TODO determine if we really only want to run tests on main branch PRs
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup environment
        id: setup-env
        uses: ./.github/actions/setup-env

        # Only check and test the packages that have changed
      - name: Code quality checks
        run: lerna run check ${{ steps.setup-env.outputs.lerna_scope }}

      - name: Test
        run: lerna run test ${{ steps.setup-env.outputs.lerna_scope }}

  visual-tests:
    name: Compare UI with baseline
    needs: build
    uses: ./.github/workflows/chromatic.yml
    with:
      onlyChanged: true
    secrets: inherit