name: Main branch update

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup environment
        uses: ./.github/actions/setup-env

      - name: Code quality checks
        run: bun run check

      - name: Test
        run: bun run test

  update-visual-test-baseline:
    name: Update visual testing baseline
    needs: build
    uses: ./.github/workflows/chromatic.yml
    with:
      onlyChanged: true
      # baseline builds are automatically approved, as they were reviewed in the PR flow
      autoApprove: true
    secrets: inherit