name: Main branch update

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    outputs:
      packages_to_install: ${{ steps.setup-env.outputs.packages_to_install }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup environment
        id: setup-env
        uses: ./.github/actions/setup-env
        with:
          packages_to_install: '*'

      - name: Code quality checks
        run: bun run check

      - name: Test
        run: bun run test
  # TODO extract the storybook package detection to some other action so that it can be reused by the baseline build
  update-ui-baseline:
    needs: build
    strategy:
      matrix:
        package_name: ${{ fromJSON(needs.build.outputs.packages_to_install) }}
    uses: ./.github/workflows/chromatic.yml
    with:
      package_name: ${{ matrix.package_name }}
      onlyChanged: false
      autoApprove: true
    secrets: inherit